name: All Tests (C++)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Detect change files
        id: changed
        uses: tj-actions/changed-files@v4

      - name: Set flags
        id: flags
        run: |
          CHANGED="${{ steps.changed.outputs.all_changed_files }}"
          run_ACL=false
          run_Competitive=false
          if echo "$CHANGED" | grep -qE '(^|\s)ac-library/'; then
            run_ACL=true
            run_Competitive=true
          elif echo "$CHANGED" | grep -qE '(^|\s)include/'; then
            run_Competitive=true
          fi
          echo "run_ACL=$run_ACL" >> $GITHUB_OUTPUT
          echo "run_Competitive=$run_Competitive" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: cpp-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Run AC-Library Test
        if: ${{ steps.flags.outputs.run_ACL == 'true' }}
        run: |
          ./scripts/run-acl-tests.sh

      - name: Run Competitive-Library Test
        if: ${{ steps.flags.outputs.run_Competitive == 'true' }}
        run: |
          ./scripts/run-competitive-tests.sh
